# Generated by Django 2.0.2 on 2018-02-28 11:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('category', models.CharField(choices=[('L', 'Long Distance'), ('S', 'Short Distance')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch_manager', models.OneToOneField(limit_choices_to={'groups__name': 'Branch Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_trips', to='fleet_management.Route')),
                ('driver', models.ForeignKey(limit_choices_to={'groups__name': 'Driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_trips', to='fleet_management.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=127)),
                ('number', models.CharField(max_length=127)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('capacity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('L', 'Light'), ('H', 'Heavy')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ok', models.BooleanField(default=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='fleet_management.Vehicle', unique_for_date='date')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInOutInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_arrived', models.BooleanField(default=False)),
                ('is_leaved', models.BooleanField(default=False)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('leaved_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_info', to='fleet_management.Route')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_info', to='fleet_management.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet_management.Vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='via',
            field=models.ManyToManyField(blank=True, to='fleet_management.Route'),
        ),
    ]
