# Generated by Django 2.0.2 on 2018-02-28 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'permissions': (('can_manage_trips', 'Can Manage Trips'),)},
        ),
        migrations.AlterModelOptions(
            name='vehiclecondition',
            options={'permissions': (('can_manage_vehicle_condition', 'Can Manage Vehicle Condition'),)},
        ),
        migrations.AlterModelOptions(
            name='vehicleinoutinfo',
            options={'permissions': (('can_manage_vehicle_in_out_info', 'Can Manage Vehicle In Out Info'),)},
        ),
    ]
