# Generated by Django 2.0.2 on 2018-02-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0002_auto_20180228_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiclecondition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicleinoutinfo',
            options={},
        ),
    ]
